# spring.application.name=user-service

# spring.datasource.url=jdbc:postgresql://localhost:5432/payflow_user_db
# spring.datasource.username=postgres
# spring.datasource.password=Postgres@2026
# spring.datasource.driver-class-name=org.postgresql.Driver

# spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=false
# spring.jpa.properties.hibernate.format_sql=true

# server.port=8081

# spring.datasource.url=jdbc:h2:mem:payflow_user_db
# spring.datasource.driverClassName=org.h2.Driver
# spring.datasource.username=sa
# spring.datasource.password=

spring.application.name=user-service

spring.datasource.url=jdbc:h2:mem:payflow_user_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.h2.console.enabled=true
spring.jpa.show-sql=true

server.port=8081

jwt.secret=your_super_secret_key_that_is_at_least_256_bits_long_1234567890abcdefghij
jwt.access-token-expiration=900000
jwt.refresh-token-expiration=604800000